Фикс просьб в баг-репорт
xtray85/space_station pull request #538
Opened 2024-03-30 00:16 UTC by Darki255

## Описание PR

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- fix: Исправлена готовка фаршированной запеченной курицы
- fix: Исправлено кушание личинки гены у унатхов
- fix: Исправлена конфетница
- fix: Исправлен GuideBook патологоанатома

2024-03-30 00:38 UTC, Darki255 commented
В рецепт надо написать,что не 5 соуса надо,а целый пакет

2024-03-30 11:54 UTC, modern-nm commented
PR не содержит ссылок на проблемы/баги, не содержит скриншотов (хотя ты указал что они есть), и PR в целом не описан как следует. 


"фикс ошибки готовки" — какой конкретно ошибки?
"Исправлена конфетница" — а что с ней было не так?

2024-03-30 14:58 UTC, modern-nm requested changes
Оформи PR. нет смысла читать код без этого

2024-03-30 15:37 UTC, Darki255 commented
> Оформи PR. нет смысла читать код без этого

Смотри

2024-03-30 20:55 UTC, Schrodinger71 commented
@Darki255 Думаю если всё подставишь и оформишь хоть так что ли, будет более менее солидно хотя бы выглядеть

![image](https://github.com/xtray85/space_station/assets/132720404/61a3e254-d897-47d7-82a5-541e3f8076ab)

2024-03-31 06:46 UTC, modern-nm requested changes
Хочется закрыть этот PR.

2024-03-31 06:46 UTC, modern-nm commented on Resources/Prototypes/ADT/Recipes/Cooking/meat_recipe.yml
> -  reagents:
Я проверил, старый рецепт с барбекю соусом работает на локалке.

2024-03-31 07:37 UTC, Darki255 commented on Resources/Prototypes/ADT/Recipes/Cooking/meat_recipe.yml
> +    FoodCondimentPacketBbq: 1
> Мне интересно что будет, если добавить в микроволновку пустой пакет FoodCondimentPacketBbq (ну или неполный/открытый). Вы не проверяли такой кейс?

С пустым тоже готовится,но игроки не могут знать об этом. Ибо они будут думать,что если положить пустой пакет,то не приготовится

2024-03-31 07:39 UTC, Darki255 commented on Resources/Prototypes/Entities/Objects/Misc/candy_bowl.yml
> +  - type: Storage
> Ладно, калаш туда засунуть нельзя. зато можно засунуть туда мышь.

Вайтлист стоит на пилюли и маленькие вещи,от того что там мышь будет,ничего плохого не будет. В реальности тараканы или другие в конфетницах могут сидеть.

2024-03-31 07:39 UTC, Darki255 commented on Resources/Prototypes/ADT/Recipes/Cooking/meat_recipe.yml
> -  reagents:
> Я проверил, старый рецепт с барбекю соусом работает на локалке.

У меня не работал,айди был не правильным

2024-03-31 08:35 UTC, modern-nm commented on Resources/Prototypes/ADT/Recipes/Cooking/meat_recipe.yml
> +    FoodCondimentPacketBbq: 1
Это интересная точка зрения. Я закрываю PR по причине неадекватности автора.

2024-03-31 08:35 UTC, closed without merging