Фиксы просьб баг-репорта
xtray85/space_station pull request #542
Opened 2024-03-31 09:39 UTC by Darki255

## Описание PR

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
-fix: Пофиксил взятие таблеток из конфетницы - https://discord.com/channels/901772674865455115/1053757139123961977/1221105738315993200
-fix: Добавил недостающий ингредиент в рецепт фаршированной курицы с овощами 
![image](https://github.com/xtray85/space_station/assets/87230164/00d44294-83ba-482f-a2e1-313cf017dc08)
-fix: Пофиксил возможность кушания личинуса у унатхов
-fix: Пофиксил ошибку руководства патологоанатома - https://discord.com/channels/901772674865455115/1053757139123961977/1220819743158833323

2024-03-31 13:52 UTC, modern-nm requested changes

2024-03-31 13:52 UTC, modern-nm commented on Resources/ServerInfo/ADT/NewRecipes.xml
> + - 1 пакет соуса барбекю
1 пакет соуса - это 10 ед. в рецепте yml указано 5 ед. Надо решить нестыковку и можно пушить.

2024-03-31 13:55 UTC, Darki255 commented on Resources/ServerInfo/ADT/NewRecipes.xml
> + - 1 пакет соуса барбекю
ok

2024-03-31 14:05 UTC, modern-nm approved these changes

2024-03-31 15:13 UTC, modern-nm commented
Failed UninitializedSaveTest [13 s]
  Error Message:
   Prototype CandyBowl modifies component on spawn: ContainerContainer. Modified yaml:
containers:
  bin-container: !type:Container
    showEnts: False
    occludes: True
    ents: []
  storagebase: !type:Container
    showEnts: False
    occludes: True
    ents: []

2024-04-01 17:44 UTC, Darki255 commented
> Failed UninitializedSaveTest [13 s] Error Message: Prototype CandyBowl modifies component on spawn: ContainerContainer. Modified yaml: containers: bin-container: !type:Container showEnts: False occludes: True ents: [] storagebase: !type:Container showEnts: False occludes: True ents: []

А где ты эту ошибку нашел?

2024-04-01 18:09 UTC, Schrodinger71 commented
> > Failed UninitializedSaveTest [13 s] Error Message: Prototype CandyBowl modifies component on spawn: ContainerContainer. Modified yaml: containers: bin-container: !type:Container showEnts: False occludes: True ents: [] storagebase: !type:Container showEnts: False occludes: True ents: []
> 
> А где ты эту ошибку нашел?

В билд тесте, почти в конце

![image](https://github.com/xtray85/space_station/assets/132720404/e5b6f7f3-4a06-4d9f-b4c4-7eb5408a84b9)

2024-04-02 00:55 UTC, PyotrIgn approved these changes

2024-04-02 00:55 UTC, merged