Rework Офицера Синего Щита
xtray85/space_station pull request #705
Opened 2024-05-18 15:40 UTC by ITamiokiI

#Описание PR
Давно необходимый реворк Офицера Синего Щита, исправляющий имеющиеся в нём ранее ошибки, недочёты, неточности. Добавляющий ему новую экипировку и арсенал, и изменяющий старую, исправляя в ней ошибки, а так же её текстурки и функционал. Итогом можно сделать то, что данная роль наконец исправлена, с точки зрения ошибок и полноценности, вопрос которой стоял с ней ранее. Роль стала приближена к своему аналогу из SS13.
ПРИМЕЧАНИЕ:
В будущем возможны ещё дополнения, и исправления ошибок.

 #Изменения
Удалено:
РПС Офицера Синего Щита был удалён, в связи с его ужасным внешним видом, и ненадобностью.

Старые текстурки вещей ОСЩ, лежащие в папке репозитория, но не использующиеся.

Мультифазовый Револьвер Офицера Синего Щита, пока что, временно удалён (Наверное.)

Изменено:

Изменены практически полностью спрайты экипировки и арсенала Офицера Синего Щита, изменён спрайт ID карты ЦК, и её разновидностей, изменён спрайт КПК ЦентКома.

ОСЩ наконец подчиняется представителям ЦентКома, а не Капитану.

Изменена стартовая экипировка ОСЩ и характеристики его экипировки и брони.

Изменено необходимое игровое время для открытия ОСЩ, теперь оно составляет :
Капитан 10 часов (≈5 смен.)
ГСБ 10 часов (≈5 смен.)
СМО 5 часов (≈3 смены.)
Ведь ОСЩ это группа Специалистов ЦК, являющееся пост-Капитанским геемплеем. (Плюс отсеет дурачков.)

Изменены и исправлены некоторые названия и описания предметов. Некоторые даже не связанны с ОСЩ, а были исправлены хаотично во время поисков необходимого файла. Так же изменена часть названий папок и файлов.

Изменено наполнение рюкзаков ОСЩ, исправлена проблема отсутствия их не заполненной версии.

Слегка изменены характеристики Скафандра ОСЩ и его бронежилета.

Демонстрация скафандра ОСЩ вместе с накидкой.
![image](https://github.com/xtray85/space_station/assets/143713810/9dcb035e-697f-46da-ac70-dadf92110e8f)
![image](https://github.com/xtray85/space_station/assets/143713810/aa21a398-193f-4df9-a61d-ab6044edc974)
![image](https://github.com/xtray85/space_station/assets/143713810/99723bae-fa3c-44df-9b24-8fcb5e717b02)
![image](https://github.com/xtray85/space_station/assets/143713810/1d0932ee-a14e-43d3-912f-56726318edfb)
![image](https://github.com/xtray85/space_station/assets/143713810/333a8b93-6e4d-4dd5-8b6d-5c35cdd81826)

Добавлено:

Добавлен шкафчик ОСЩ и его наполнение, состоящие из его запасной экипировки и одежды, оружейного кейса и аптечек.

Добавлена новая экипировка ОСЩ, а так же текстурки для неё:

Накидка Офицера Синего Щита(Просто плащ)

Очки Офицера Синего Щита - Охранные очки со своей текстуркой и Медицинаким худом в придачу к СБшному.

Изменено нижнее бельё ОСЩ, и добавлены носки и чулки, вместе с коробкой набора нижнего белья ОСЩ, которое спавнится в его шкафу.

Добавлен оружейный кейс, на данный момент только для ОСЩ, хранящий в себе его оружие.(Про него позже.)

Охранно-медицинский пояс - Пояс способный помещать в себе как и Сбшные вещи, так и медицинские. Так же может содержать оружие и патроны. Имеет как пустую версию, так и стартовую для ОСЩ.
![image](https://github.com/xtray85/space_station/assets/143713810/d0e3ce9f-c96e-4cf9-8a65-0ceaa7842abc)

Естественно добавлена одежда ОСЩ, комбинезоны (Они же костюмы.), водолазки, изменён один берет и добавлен второй. Добавлена куртка, имеющая небольшую защиту от порезов и ударов. Добавлен вещмешок и сумка ОСЩ, которой почему-то до этого не было. (Но спрайты их были.)

Общий план.
![image](https://github.com/xtray85/space_station/assets/143713810/52dc7e1b-23da-4d5c-b832-1783f716111b)

Костюмы и водолазка.
![image](https://github.com/xtray85/space_station/assets/143713810/6357ca45-a1cc-460a-b3cf-1e6109a87d7b)

Нижнее бельё.
![image](https://github.com/xtray85/space_station/assets/143713810/68fdcda7-e931-46d1-94f4-375ac6445f49)

Добавлен Энергетический Меч-Револьвер.
Эксклюзивное оружие Офицера Синего Щита, появляющиеся раундстартом в его шкафчике, в оружейном кейсе, в месте с 3-мя Барабанными Батареями Револьвера. Является смертоносным объединением револьвера и светового меча, который может как и резать, так и стрелять. Является 5-ти зарядным, после разрядки батарею можно снять и зарядить, заменив на другую.

![0tIxipI](https://github.com/xtray85/space_station/assets/143713810/601e43de-4286-4ecb-9d3b-c9610940f579)

![Content Client_AtCMHRfXn1](https://github.com/xtray85/space_station/assets/143713810/0ea8beff-025a-4d50-b078-86b43a937d39)

![Content Client_QVddRhG3xi](https://github.com/xtray85/space_station/assets/143713810/d7af93a0-4759-4269-9d7e-e1620a113b93)

![PZNFvx0](https://github.com/xtray85/space_station/assets/143713810/d23ee3b7-d4bd-4247-a63d-d07422cc6170)
![AO5W9Pm](https://github.com/xtray85/space_station/assets/143713810/954288f2-009c-405a-a09b-5c730151d0d8)

Добавлена фигурка ОСЩ, потому что я могу.

(Список не полный, я мог что-то да забыть.)

#Проверки
- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, или этот PR этого не требует.

#Чейджьлог
:cl: Tamioki&RevengentRat
(Не писал, изменения выше, всё равно он автоматически не добавится.)
Пока что не мерджить, нужно сделать ченджьлог.

2024-05-18 21:52 UTC, Schrodinger71 requested changes
убрать дубликаты в `.ftl` файлах

2024-05-18 21:52 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/Objects/Misc/identification_cards.ftl
> +    .desc = { ent-CentcomIDCard.desc }
Файл с такими же переводами уже существует

![image](https://github.com/xtray85/space_station/assets/132720404/ec416ef4-a822-4807-bf57-5fa42e9c940d)

2024-05-19 21:21 UTC, 1Stepka1 commented
Смотрю на изменения и вижу что после моей сортировки пару файлов существовать и не будет или будут категории для тех изменений которые вписаны в отдельные файлы, в том числе в файлы визардов, так что даже не знаю что делать в этой ситуации

2024-05-20 11:16 UTC, Schrodinger71 commented
@1Stepka1 укажи конкретней в каких местах, что надобно подправить

2024-05-20 13:40 UTC, ITamiokiI commented
> Смотрю на изменения и вижу что после моей сортировки пару файлов существовать и не будет или будут категории для тех изменений которые вписаны в отдельные файлы, в том числе в файлы визардов, так что даже не знаю что делать в этой ситуации Так же кое-что не совсем соответствует нормальному распределению в сборке

Вопрос, а это уже мерджнуто? Ну, сортировка. Если нет, то вопрос, а зачем нам изменять свой ПР под то что ещё не появилось в сборке? (Хотя может быть к моменту мерджа этого ПРа, сортировка уже будет мерджнута.) Ну, просто если я пофикшу это сейчас, и это мерджнут, то я не вижу смысла редактировать его под то что ещё в процессе... Ибо перемещение всё под твою сортировку, будет потрачено ещё время, а мы на это тратить время не очень хотим. Его не так много.

2024-05-20 13:44 UTC, ITamiokiI commented on Resources/Locale/ru-RU/ADT/Objects/Misc/identification_cards.ftl
> +    .desc = { ent-CentcomIDCard.desc }
А вот это дап. Я скорее всего тут ошибся. Пофикшу, это всё?

2024-05-20 16:37 UTC, Schrodinger71 commented
Ошибки в Ямлинтере
```
Unhandled exception. System.AggregateException: One or more errors occurred. (CLIENT: 6,901s [ERRO] eng: Exception whilst loading prototypes from /Prototypes/ADT/Entities/Clothing/Ears/headsets.yml:
System.ArgumentException: An item with the same key has already been added. Key: parent
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
```

![image](https://github.com/xtray85/space_station/assets/132720404/4f0908cc-6458-4f73-bacc-aa6e08c0862c)

2024-05-22 19:51 UTC, Schrodinger71 commented
мдам.. конфликты

2024-05-23 21:22 UTC, Schrodinger71 commented
Поправить это в билд тестах и перемапить мапы
```  Failed StorageSizeArbitrageTest [13 ms]
  Error Message:
     Found storage arbitrage on BaseWeaponCaseNTBS
Assert.That(itemSys.GetSizePrototype(storage.MaxItemSize.Value).Weight, Is.LessThanOrEqualTo(itemSys.GetSizePrototype(item.Size).Weight))
  Expected: less than or equal to 2
  But was:  16```

2024-05-23 21:31 UTC, Schrodinger71 requested changes
### Исправить ошибку в билд тестах и перемапить карты
```
  Failed StorageSizeArbitrageTest [13 ms]
  Error Message:
     Found storage arbitrage on BaseWeaponCaseNTBS
Assert.That(itemSys.GetSizePrototype(storage.MaxItemSize.Value).Weight, Is.LessThanOrEqualTo(itemSys.GetSizePrototype(item.Size).Weight))
  Expected: less than or equal to 2
  But was:  16
```

### При надевании капюшона от зимней куртке ОСЩ, его цвет другой. Тьфу, фикс к этому уже замерджен https://github.com/xtray85/space_station/pull/722
![image](https://github.com/xtray85/space_station/assets/132720404/04e590fd-44a4-47bc-9b84-289feb46399d)

### Разные размеры аптечек в инвентаре одинаковых по объёму
![image](https://github.com/xtray85/space_station/assets/132720404/15174e8f-05f9-412b-8662-dbeabd4f6dc0)

### У энергокинжала урон 20, у двухклинкового сумарный 24, у обычного энерго меча 30. Уменьшить урон энергокинжала ОСЩ до 20-25
![image](https://github.com/xtray85/space_station/assets/132720404/456b55a3-3a0b-4581-927f-5a68bda99fe7)

### У агоста нет доступа ОСЩ
![image](https://github.com/xtray85/space_station/assets/132720404/d8298d25-124e-4d56-b00e-4a1b73e5c20f)

2024-06-11 16:22 UTC, Schrodinger71 approved these changes

2024-06-11 16:23 UTC, merged