Порт Р.П.А. с Сирены
xtray85/space_station pull request #729
Opened 2024-05-24 00:56 UTC by Us3rn4me228

## Описание PR
Продолжаем портировать годноту с Сирены. На этот раз настала очередь Р.П.А. - пинпоинтера аномалий, который является хайриском Научрука. Крайне полезная вещь, не теряйте.

**Медиа**
![image](https://github.com/xtray85/space_station/assets/143436581/9ff5d1ee-13da-4097-a78d-ae95d23e359c)
![image](https://github.com/xtray85/space_station/assets/143436581/71df38e9-3372-438a-a642-bc8b8243a1e1)
![image](https://github.com/xtray85/space_station/assets/143436581/7abe61e0-91f1-4490-a2f8-442d1d3e919c)
![image](https://github.com/xtray85/space_station/assets/143436581/fc72d0aa-1c13-4619-8fa8-4a34eeb1e644)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Username228
- add: Добавлен Р.П.А. - пинпоинтер аномалий.
- add: Добавлено задание для предателя на кражу Р.П.А.
- add: Для Р.П.А. сделан новый спрайт.

2024-05-24 21:51 UTC, Schrodinger71 requested changes
### Ошибки в билдтестах.  Ещё бы для баланса этому устройству нужно бы сделать потребление энергии от батарейки

```
  Failed NoCargoBountyArbitrageTest [4 s]
  Stack Trace:
  
1)    at Content.IntegrationTests.Pair.TestPair.OnDirtyDispose() in /home/runner/work/space_station/space_station/Content.IntegrationTests/Pair/TestPair.Recycle.cs:line 32
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Content.IntegrationTests.Pair.TestPair.OnDirtyDispose()
   at Content.IntegrationTests.Pair.TestPair.DisposeAsync() in /home/runner/work/space_station/space_station/Content.IntegrationTests/Pair/TestPair.Recycle.cs:line 102
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Content.IntegrationTests.Pair.TestPair.DisposeAsync()
   at Content.IntegrationTests.Tests.CargoTest.NoCargoBountyArbitrageTest() in /home/runner/work/space_station/space_station/Content.IntegrationTests/Tests/CargoTest.cs:line 93
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
```

```
Failed NoStaticPriceAndStackPrice [42 ms]
  Error Message:
     Assert.That(delta, Is.EqualTo(targetDelta))
  Expected: 1
  But was:  0

  Stack Trace:
     at Content.IntegrationTests.Pair.TestPair.SyncTicks(Int32 targetDelta) in /home/runner/work/space_station/space_station/Content.IntegrationTests/Pair/TestPair.Timing.cs:line 60
   at Content.IntegrationTests.PoolManager.GetServerClientPair(PoolSettings poolSettings) in /home/runner/work/space_station/space_station/Content.IntegrationTests/PoolManager.cs:line 248
   at Content.IntegrationTests.PoolManager.GetServerClientPair(PoolSettings poolSettings) in /home/runner/work/space_station/space_station/Content.IntegrationTests/PoolManager.cs:line 266
   at Content.IntegrationTests.PoolManager.GetServerClient(PoolSettings poolSettings) in /home/runner/work/space_station/space_station/Content.IntegrationTests/PoolManager.cs:line 192
   at Content.IntegrationTests.Tests.CargoTest.NoStaticPriceAndStackPrice() in /home/runner/work/space_station/space_station/Content.IntegrationTests/Tests/CargoTest.cs:line 99
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass3_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

1)    at Content.IntegrationTests.Pair.TestPair.SyncTicks(Int32 targetDelta) in /home/runner/work/space_station/space_station/Content.IntegrationTests/Pair/TestPair.Timing.cs:line 60
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Content.IntegrationTests.Pair.TestPair.SyncTicks(Int32 targetDelta)
   at Content.IntegrationTests.PoolManager.GetServerClientPair(PoolSettings poolSettings) in /home/runner/work/space_station/space_station/Content.IntegrationTests/PoolManager.cs:line [248](https://github.com/xtray85/space_station/actions/runs/9217012454/job/25358304114?pr=729#step:10:249)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
```

2024-05-24 23:50 UTC, Us3rn4me228 commented
> ### Ошибки в билдтестах. Ещё бы для баланса этому устройству нужно бы сделать потребление энергии от батарейки
> ```
>   Failed NoCargoBountyArbitrageTest [4 s]
>   Stack Trace:
>   
> 1)    at Content.IntegrationTests.Pair.TestPair.OnDirtyDispose() in /home/runner/work/space_station/space_station/Content.IntegrationTests/Pair/TestPair.Recycle.cs:line 32
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Content.IntegrationTests.Pair.TestPair.OnDirtyDispose()
>    at Content.IntegrationTests.Pair.TestPair.DisposeAsync() in /home/runner/work/space_station/space_station/Content.IntegrationTests/Pair/TestPair.Recycle.cs:line 102
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Content.IntegrationTests.Pair.TestPair.DisposeAsync()
>    at Content.IntegrationTests.Tests.CargoTest.NoCargoBountyArbitrageTest() in /home/runner/work/space_station/space_station/Content.IntegrationTests/Tests/CargoTest.cs:line 93
>    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
> ```
> 
> ```
> Failed NoStaticPriceAndStackPrice [42 ms]
>   Error Message:
>      Assert.That(delta, Is.EqualTo(targetDelta))
>   Expected: 1
>   But was:  0
> 
>   Stack Trace:
>      at Content.IntegrationTests.Pair.TestPair.SyncTicks(Int32 targetDelta) in /home/runner/work/space_station/space_station/Content.IntegrationTests/Pair/TestPair.Timing.cs:line 60
>    at Content.IntegrationTests.PoolManager.GetServerClientPair(PoolSettings poolSettings) in /home/runner/work/space_station/space_station/Content.IntegrationTests/PoolManager.cs:line 248
>    at Content.IntegrationTests.PoolManager.GetServerClientPair(PoolSettings poolSettings) in /home/runner/work/space_station/space_station/Content.IntegrationTests/PoolManager.cs:line 266
>    at Content.IntegrationTests.PoolManager.GetServerClient(PoolSettings poolSettings) in /home/runner/work/space_station/space_station/Content.IntegrationTests/PoolManager.cs:line 192
>    at Content.IntegrationTests.Tests.CargoTest.NoStaticPriceAndStackPrice() in /home/runner/work/space_station/space_station/Content.IntegrationTests/Tests/CargoTest.cs:line 99
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass3_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
> 
> 1)    at Content.IntegrationTests.Pair.TestPair.SyncTicks(Int32 targetDelta) in /home/runner/work/space_station/space_station/Content.IntegrationTests/Pair/TestPair.Timing.cs:line 60
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Content.IntegrationTests.Pair.TestPair.SyncTicks(Int32 targetDelta)
>    at Content.IntegrationTests.PoolManager.GetServerClientPair(PoolSettings poolSettings) in /home/runner/work/space_station/space_station/Content.IntegrationTests/PoolManager.cs:line [248](https://github.com/xtray85/space_station/actions/runs/9217012454/job/25358304114?pr=729#step:10:249)
>    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
> ```

знал бы я как их фиксить ещё и что их вызывает
а сам РПА итак забаланшен тем, что это хайриск предмет, на который есть задание у синдиката
по сему делать пинпоинтер на батарейках малость бессмысленно

2024-05-25 17:13 UTC, Schrodinger71 commented
а ну всё, вроде пропали ошибки

2024-05-25 20:42 UTC, Us3rn4me228 commented
> а ну всё, вроде пропали ошибки

хорошо, тогда аппрувни пожалуйста
чтобы плашка о требуемых изменениях не висела

2024-05-26 07:43 UTC, KashRas2 commented
описание лучше поменять на что-то благоприятное

2024-05-26 16:43 UTC, Schrodinger71 approved these changes

2024-05-26 16:43 UTC, merged