Chief engineer's gas mask
xtray85/space_station pull request #733
Opened 2024-05-29 07:02 UTC by Alazell

Об прототипе:
_id - ADTClothingMaskGasCE
противогаз старшего инженера
Это элитный противогаз Старшего Инженера, которому может позавидовать даже Центральное Командование. Защищает от сварки.
Защита от:
  Blunt: 5%
  Caustic: 10%
  Radiation: 20%
  Heat: 20%_

Помимо прототипа:
- Изменена **RU** локализация для противогаза
- Добавлена задача для вора - украсть противогаз СИ
- Изменён шкаф с скафандром СИ (обычная маска заменена на элитную)

ТРЕБУЕТСЯ:
Спрайты для рептилий и вульп, у них носы вылезают. Морды. Да. (забавно)

Примечание: Готовый спрайт на мордашки сильно отличается от своего брата ICON, где присутствуют совершенно другие формы и цвета на противогазе. Я думаю это надо исправить.

2024-05-29 07:11 UTC, Alazell commented
Ура, я не огузок!!

2024-05-29 08:00 UTC, FaDeOkno submitted a review, later dismissed
👍

2024-05-29 10:07 UTC, Schrodinger71 commented
Спрайты долго ждать? В этот пр будут закинуты новые коммиты?

2024-05-29 11:25 UTC, 1Stepka1 commented
Быстро конечно закончили, но есть у меня дополнение
Переместить stealgroup из Resources/Prototypes/Objectives/stealTargetGroups.yml в Resources/Prototypes/ADT/Objectives/stealTargetGroups.yml

2024-05-29 11:51 UTC, Schrodinger71 commented
*уээ, это Котя апрувнул без анализа*

2024-05-29 11:55 UTC, Schrodinger71 requested changes
Разжалован в модеры

2024-06-02 19:41 UTC, Schrodinger71 approved these changes

2024-06-02 19:41 UTC, merged