Локализация аплинка и мелочей
xtray85/space_station pull request #737
Opened 2024-05-30 16:55 UTC by Lonkuk

## Описание PR

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Локализация аплинка, ратвара, криков боли и различных мелочей.

2024-05-31 23:09 UTC, Schrodinger71 commented
ох ё маё, мне кажется тут многое стоило по папкам ADT

2024-06-03 21:41 UTC, Lonkuk commented
А что и куда например?.. В ru-RU/ADT в основном лежит локализация от Prototypes/ADT. Я в основном перевёл то, что было от апстрима (и было не переведено 2 месяца или больше...)

2024-06-05 01:34 UTC, modern-nm requested changes
тест, не обращай внимания, шрёдя тебе объяснит

2024-06-05 01:35 UTC, Schrodinger71 approved these changes

2024-06-06 18:29 UTC, merged