added new posters
xtray85/space_station pull request #765
Opened 2024-06-23 05:47 UTC by TORGOVEC471

## Описание PR

Добавлены 4 новых постера (Error, NoBad, NoGood, GasAttack)
**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Torgovec
- add: Добавлены 4 новых плаката.

2024-06-23 08:44 UTC, modern-nm requested changes

2024-06-23 08:44 UTC, modern-nm commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
путь .ftl файла должен совпадать с путём до .yml
~Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl~
Resources/Locale/ru-RU/ss14-ru/prototypes/ADT/entities/structures/wallmount/signs/posters.ftl
но у нас там бардак, так что пока не обращай внимания

2024-06-23 08:44 UTC, modern-nm commented on Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
> +    sprite: ADT/Objects/Decoration/poster_syndycat.rsi
~ADT/Objects/Decoration/poster_syndycat.rsi~
ADT/Objects/Decoration/poster_syndicate.rsi
исправь и старайся писать грамотно, ибо через пол года, тот кто будет искать постер синдиката столкнётся с трудностями (и кринжанёт)

2024-06-23 20:08 UTC, Schrodinger71 approved these changes
Ну теперь вроде всё ок

2024-06-24 01:37 UTC, modern-nm approved these changes

2024-06-24 01:48 UTC, merged